
dataset_bucket: nfwf-tool/natureserve

user_shapes_bucket: nfwf-tool-user-shapes
user_shapes_folder: natureserve

datasets:
  - name: threat
    input_files:
      - TargetedWatershedThreat8.10x10.tif

  - name: exposure
    input_files:
      - TargetedWatershedExposure8.tif

  - name: asset
    input_files:
      - TargetedWatershedAsset8.tif

  - name: fishandwildlife
    input_files:
      - TargetedWatershedFishandWildlife8.tif

  - name: hubs
    input_files:
      - TargetedWatershedHubs8.tif

