
git:
  depth: 3

sudo: required

services:
- docker

install:
- "sudo apt install awscli"
- "docker pull lambci/lambda:build-python3.6"

script: docker run --rm -it -v $PWD:/var/task lambci/lambda:build-python3.6 /bin/bash -c './run-tests.sh'

#deploy:
#- provider: script
#  script: ./deploy.sh $TRAVIS_BRANCH
#  on:
#    all_branches: true
#    condition: TRAVIS_BRANCH =~ ^staging|production$

#after_deploy: ./test-api.sh $TRAVIS_BRANCH

