
git:
  depth: 3

sudo: required

services:
  - docker

install:
  - "docker pull lambci/lambda:build-python3.6"

script:
  - "docker run --rm -v $PWD:/var/task -it lambci/lambda:build-python3.6 /bin/sh -c 'run-tests.sh'"

before_deploy:
  - "docker run --rm -v $PWD:/var/task -it lambci/lambda:build-python3.6 /bin/sh -c 'pre-deploy.sh'"

deploy:
  - ./deploy-dev.sh

after_deploy:
  - ./test-api.sh


