version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Preparing environment
      - ./build.sh
  post_build:
    commands:
      - aws cloudformation package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket nemac-cloudformation
      - aws cloudformation deploy --template-file packaged.yaml --stack-name nfwf-tool-api-dev --capabilities CAPABILITY_IAM
