
dataset_bucket: nfwf-tool

user_shapes_bucket: nfwf-tool-user-shapes

test:
  continental_us: [35.89, -79.45]
  puerto_rico: [18.28, -66.42]
  us_virgin_islands: [17.77, -64.79]
  northern_mariana_islands: []

vrt:
  continental_us: continental_us.vrt
  puerto_rico: puerto_rico.vrt
  us_virgin_islands: virgin_islands.vrt
  northern_mariana_islands: northern_mariana_islands.vrt

datasets:

  continental_us:
    - name: exposure
      path: CONUS_ExposureIndex_10class_111918.tif
    - name: asset
      path: CONUS_AssetIndex_10class_111918.tif
    - name: threat
      path: CONUS_ThreatIndex_10class_111918.tif
    - name: aquatic
      path: CONUS_AquaticIndex_clip_111218.tif
    - name: terrestrial
      path: CONUS_TerrestrialIndex_clip_111218.tif
    - name: hubs
      path: CONUS_ResilienceHubs_121918.tif
    - name: crit_infra
      path: asset-inputs/CONUS_CritInfra_shift_111518.tif
    - name: crit_facilities
      path: asset-inputs/CONUS_CritFac_shift_111918.tif
    - name: pop_density
      path: asset-inputs/CONUS_Population_shift_110718.tif
    - name: social_vuln
      path: asset-inputs/CONUS_SocVul_shift_110718.tif
    - name: drainage
      path: threat-inputs/CONUS_DrainDev_shift_111418.tif
    - name: erosion
      path: threat-inputs/CONUS_Erosion_111418.tif
    - name: floodprone_areas
      path: threat-inputs/CONUS_Floodprone_shift_111418.tif
    - name: geostress
      path: threat-inputs/CONUS_Geostress_shift_111518.tif
    - name: sea_level_rise
      path: threat-inputs/CONUS_SLR_shift_110918.tif
    - name: slope
      path: threat-inputs/CONUS_Slope_shift_111918.tif
    - name: storm_surge
      path: threat-inputs/CONUS_StormSurge_shift_111618.tif

  puerto_rico:
    - name: exposure
      path: puerto-rico/byte/PR_ExposureIndex_10class_021120_clip.tif
    - name: asset
      path: puerto-rico/byte/PR_AssetIndex_10class_021020_clip.tif
    - name: wildlife
      path: puerto-rico/byte/PR_CombinedWildlife_6class_040320.tif
    - name: crit_facilities
      path: puerto-rico/byte/PR_CriticalFacilities_v2_clip.tif
    - name: crit_infra
      path: puerto-rico/byte/PR_CriticalInfrastructure_v2_clip.tif
    - name: erosion
      path: puerto-rico/byte/PR_ErodibleSoils_v2_clip.tif
    - name: floodprone_areas
      path: puerto-rico/byte/PR_FloodproneAreas_v2_clip.tif
    - name: impermeable
      path: puerto-rico/byte/PR_Impermeable_v2_clip.tif
    - name: landslides
      path: puerto-rico/byte/PR_Landslides_v2_clip.tif
    - name: low_areas
      path: puerto-rico/byte/PR_LowLyingAreas_v2_clip.tif
    - name: marine
      path: puerto-rico/byte/PR_MarineIndex_4class.tif
    - name: pop_density
      path: puerto-rico/byte/PR_PopulationDensity_v2_clip.tif
    - name: sea_level_rise
      path: puerto-rico/byte/PR_SLR_v2_clip.tif
    - name: social_vuln
      path: puerto-rico/byte/PR_SocialVulnerability_v2_clip.tif
    - name: storm_surge
      path: puerto-rico/byte/PR_StormSurge_v2_clip.tif
    - name: terrestrial
      path: puerto-rico/byte/PR_TerrestrialIndex_4class.tif
    - name: threat
      path: puerto-rico/byte/PR_ThreatIndex_10class_021120_clip.tif
    - name: tsunami
      path: puerto-rico/byte/PR_Tsunami_v2_clip.tif

  us_virgin_islands:
    - name: exposure
      path: us-virgin-islands/byte/USVI_ExposureIndex_10class_021220_clip.tif
    - name: threat
      path: us-virgin-islands/byte/USVI_ThreatIndex_10class_021220_clip.tif
    - name: asset
      path: us-virgin-islands/byte/USVI_AssetIndex_10class_021020_clip.tif
    - name: wildlife
      path: us-virgin-islands/byte/USVI_CombinedWildlife_6class_040320.tif
    - name: crit_facilities
      path: us-virgin-islands/byte/USVI_CriticalFacilities_v2_clip.tif
    - name: crit_infra
      path: us-virgin-islands/byte/USVI_CriticalInfrastructure_v2_clip.tif
    - name: erosion
      path: us-virgin-islands/byte/USVI_ErodibleSoils_v2_clip.tif
    - name: floodprone_areas
      path: us-virgin-islands/byte/USVI_FloodproneAreas_v2_clip.tif
    - name: impermeable
      path: us-virgin-islands/byte/USVI_Impermeable_v2_clip.tif
    - name: low_areas
      path: us-virgin-islands/byte/USVI_LowLyingAreas_v2_clip.tif
    - name: marine
      path: us-virgin-islands/byte/USVI_MarineIndex_4class.tif
    - name: pop_density
      path: us-virgin-islands/byte/USVI_PopulationDensity_v2_clip.tif
    - name: sea_level_rise
      path: us-virgin-islands/byte/USVI_SLR_v2_clip.tif
    - name: social_vuln
      path: us-virgin-islands/byte/USVI_SocialVulnerability_v2_clip.tif
    - name: storm_surge
      path: us-virgin-islands/byte/USVI_StormSurge_v2_clip.tif
    - name: terrestrial
      path: us-virgin-islands/byte/USVI_TerrestrialIndex_4class.tif


