
dataset_bucket: nfwf-tool/natureserve

user_shapes_bucket: nfwf-tool-user-shapes/natureserve

datasets:
  - name: exposure
    input_files:
      - ./tests/data/exposure_sample.tif

  - name: asset
    input_files:
      - ./tests/data/asset_sample.tif

  - name: threat
    input_files:
      - ./tests/data/threat_sample.tif

  - name: fishandwildlife
    input_files:
      - ./tests/data/fishandwildlife_sample.tif

  - name: hubs
    input_files:
      - ./tests/data/hubs_sample.tif

