
dataset_bucket: nfwf-tool

user_shapes_bucket: nfwf-tool-user-shapes

datasets:
  - name: exposure
    input_files:
      - CONUS_ExposureIndex_10class_111918.tif

  - name: asset
    input_files:
      - CONUS_AssetIndex_10class_111918.tif

  - name: threat
    input_files:
      - CONUS_ThreatIndex_10class_111918.tif

  - name: aquatic
    input_files:
      - CONUS_AquaticIndex_clip_111218.tif

  - name: terrestrial
    input_files:
      - CONUS_TerrestrialIndex_clip_111218.tif

  - name: hubs
    input_files:
      - WestCoastHubs_081718.tif
      - EastCoastHubs_081718.tif

  - name: crit_infra
    folder: asset-inputs
    input_files:
      - CONUS_CritInfra_shift_111518.tif

  - name: crit_facilities
    folder: asset-inputs
    input_files:
      - CONUS_CritFac_shift_111918.tif

  - name: pop_density
    folder: asset-inputs
    input_files:
      - CONUS_Population_shift_110718.tif

  - name: social_vuln
    folder: asset-inputs
    input_files:
      - CONUS_SocVul_shift_110718.tif

  - name: drainage
    folder: threat-inputs
    input_files:
      - CONUS_DrainDev_shift_111418.tif

  - name: erosion
    folder: threat-inputs
    input_files:
      - CONUS_Erosion_111418.tif

  - name: floodprone_areas
    folder: threat-inputs
    input_files:
      - CONUS_Floodprone_shift_111418.tif

  - name: geostress
    folder: threat-inputs
    input_files:
      - CONUS_Geostress_shift_111518.tif

  - name: sea_level_rise
    folder: threat-inputs
    input_files:
      - CONUS_SLR_shift_110918.tif

  - name: slope
    folder: threat-inputs
    input_files:
      - CONUS_Slope_shift_111918.tif

  - name: storm_surge
    folder: threat-inputs
    input_files:
      - CONUS_StormSurge_shift_111618.tif
