
dataset_bucket: nfwf-tool/
config_bucket:  nfwf-tool/dataset-config/

datasets:
  - name: exposure
    input_files:
      - CA_ExposureIndex_070218.tif
      - Gulf_ExposureIndex_062018.tif
      - NA_ExposureIndex_070218.tif
      - PNW_ExposureIndex_071118.tif
      - SA_v2_ExposureIndex_071018.tif

  - name: asset
    input_files:
      - CA_AssetIndex_111317.tif
      - Gulf_AssetIndex_100317.tif
      - NA_AssetIndex_100217.tif
      - PNW_AssetIndex_040618.tif
      - SA_v2_AssetIndex_053118.tif

  - name: threat
    input_files:
      - CA_ThreatIndex_070218.tif
      - Gulf_ThreatIndex_062018.tif
      - NA_ThreatIndex_070218.tif
      - PNW_ThreatIndex_071118.tif
      - SA_v2_ThreatIndex_071018.tif

  - name: aquatic
    input_files:
      - CA_HUC10_AquaticIndex_071018.tif
      - Gulf_HUC10_AquaticIndex_070918.tif
      - NA_HUC10_AquaticIndex_070918_2.tif
      - PNW_HUC10_AquaticIndex_071018.tif
      - SA_v2_AquaticIndex_053118.tif

  - name: terrestrial
    input_files:
      - CA_HUC10_TerrestrialIndex_071018.tif
      - Gulf_HUC10_TerrestrialIndex_070918.tif
      - NA_HUC10_TerrestrialIndex_070918.tif
      - PNW_HUC10_TerrestrialIndex_071018.tif
      - SA_v2_TerrestrialIndex_053118.tif

  - name: hubs
    input_files:
      - ca_hubs_080918.tif
      - gulf_hubs_080918.tif
      - na_hubs_080918.tif
      - nw_hubs_080918.tif
      - sa_hubs_080918.tif

  - name: crit_infra
    folder: asset-inputs
    input_files:
      - CA_CritInfra_Shift_111317.tif
      - Gulf_CritInfra_shift_100317.tif
      - NA_CriticalInfrastructure_100217.tif
      - PNW_CritInfrastructure_shift_040618.tif
      - SA_v2_CritInfrastructure_shift_053118.tif

  - name: crit_facilities
    folder: asset-inputs
    input_files:
      - CA_CriticalFacilities_shift_102617.tif
      - Gulf_CritFac5_shift_091817.tif
      - NA_CritFac_Recl5.tif
      - PNW_CriticalFacilities_shift.tif
      - SA_v2_CriticalFacilities_shift_053018.tif

  - name: pop_density
    folder: asset-inputs
    input_files:
      - CA_PopDensity_shift_071117.tif
      - Gulf_PopDensity_shift_061517.tif
      - NA_CPopDens.tif
      - PNW_PopDensity_shift_031918.tif
      - SA_v2_PopDensity_shift_053018.tif

  - name: social_vuln
    folder: asset-inputs
    input_files:
      - CA_SocVuln_shift_102617.tif
      - Gulf_SoVl_050917.tif
      - NA_SoVl_shift.tif
      - PNW_SocVulnerability_shift_031918.tif
      - SA_v2_SocVuln_shift_053018.tif

  - name: drainage
    folder: threat-inputs
    input_files:
      - CA_DrainageDev_shift_021318.tif
      - Gulf_DrainageDev_Reclass_062018.tif
      - NA_DrainDev_Reclass_070218.tif
      - PNW_DrainDev_Reclass_NEW.tif
      - SA_v2_DrainDev_shift_071018.tif

  - name: erosion
    folder: threat-inputs
    input_files:
      - CA_ErosionB_shift_051018.tif
      - Gulf_ErosionB_shift_051018.tif
      - NA_ErosionB_050817.tif
      - PNW_ErosionB_shift_051018.tif
      - SA_v2_ErosionB_shift_053018.tif

  - name: floodprone_areas
    folder: threat-inputs
    input_files:
      - CA_FloodproneAreas_shift_071417.tif
      - Gulf_Floodprone_shift_062217.tif
      - NA_Floodprone_5_8_17.tif
      - PNW_FloodproneAreas_shift_041118.tif
      - SA_v2_FloodproneAreas_shift_053018.tif

  - name: geostress
    folder: threat-inputs
    input_files:
      - CA_Geostress_shift_051118.tif
      - Gulf_Geostress_shift_051118.tif
      - NA_geostress_050818.tif
      - PNW_Geostress_shift_051118.tif

  - name: sea_level_rise
    folder: threat-inputs
    input_files:
      - CA_SLR_shift_071717.tif
      - Gulf_SLRshift.tif
      - NA_SLR_5_8_17.tif
      - PNW_SLR_shift_041318.tif
      - SA_v2_SLR_shift_053018.tif

  - name: slope
    folder: threat-inputs
    input_files:
      - CA_Slope_Shift_071117.tif
      - Gulf_Slope_050917.tif
      - NA_Slope_5_8_17.tif
      - PNW_Slope_shift_031918.tif
      - SA_v2_SLR_shift_053018.tif

  - name: storm_surge
    folder: threat-inputs
    input_files:
      - Gulf_StormSurge_shift_121117.tif
      - NA_StormSurge_shift_121117.tif
      - SA_v2_StormSurge_shift_053018.tif
